version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_missionary
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: missionary
      MYSQL_USER: root
      MYSQL_PASSWORD: 12345
    ports:
      - "3306:3306"  # Мапим порт для доступа снаружи (опционально)
    volumes:
      - mysql_data:/var/lib/mysql  # Сохраняем данные БД
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql  # Импортируем дамп при старте (если есть)
    networks:
      - app-network

  app:
    build: .  # Путь к Dockerfile (корень проекта)
    container_name: spring_app
    ports:
      - "8080:8080"  # Порт приложения
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/missionary
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 12345
    depends_on:
      - mysql
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network: