# Используем базовый образ Java
FROM eclipse-temurin:17-jdk-jammy

# Рабочая директория внутри контейнера
WORKDIR /app

# Копируем собранный JAR-файл в контейнер
COPY target/Missionary-0.0.1-SNAPSHOT.jar app.jar

# Открываем порт, на котором работает приложение
EXPOSE 3333

# Команда для запуска приложения
ENTRYPOINT ["java", "-jar", "app.jar"]